[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/v1/health/live"
healthcheckTimeout = 120
preDeployCommand = "/usr/local/bin/pre-deploy.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
